### ISSUE TITLE
Implement Metanorma JIS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#1]
JIS are Japan Industrial Standards.

The requirements are stated in JIS Z 8301:2019, which is documented in (https://github.com/metanorma/mn-samples-jis/issues/1) .

A sample document to format is provided in (https://github.com/metanorma/jis-example-report/issues/1).

The corresponding Word Draft document templates are located at:
* https://github.com/metanorma/mn-samples-jis/tree/main/reference-docs/JDT2019

The output formats are Word and PDF.

Dependencies:
* [ ] https://github.com/relaton/relaton-jis/issues/1
* [x] https://github.com/metanorma/jis-example-report/issues/1
* [x] https://github.com/metanorma/mn-samples-jis/issues/1
* [x] https://github.com/metanorma/metanorma-iso/issues/948 (not sure if this can be done in time)

**Comment by ronaldtse** [comment]
Localization of terms

| ISO | JIS |
|--|--|
|Standard | 規格 |
|Amendment| 追補 |
| TOC | 目次|
| Annex | 附属書 |
| Scope | 適用範囲 |
| Normative references | 引用規格|
| Terms and definitions | 用語及び定義|
| Bibliography | 参考文献 | 
| Foreword | まえがき |
| Blank page | 白紙 | 
| Standard | 規格 |
| International Standard | 日本産業規格 (Japanese industrial standard)| 
| Technical Specification | 標準仕様書(TS)|
| Technical Report | 標準報告書 |
| (all parts) | (規格群) (standards group)|
| Paragraph | 段落 |
| Note | 注記 |
| Note to entry (for terms) | 注釈 | 
| Preferred term | 優先用語 |
| Admitted term | 代替用語|
| Deprecated term | 推奨しない用語 |
| Term | 用語 |
| Definition | 定義 |
| Footnote | 注 (format: "注 a)"|
| Explanation | 解説 (supplementary content section for a JIS that provides additional explanation) | 
| Part | 部 (in JIS the subpart is considered part of the part, e.g. "第1部", "第3-2部")|
| Clause | 箇条 |
| Subclause | 細分箇条 |
|Example / Example 1 | 例 / 例 1|
|Table | 表 |
| Table 3-7| 表 3~表 7 |
| Table continuation: Figure x -- {title} (continued) | 図 x-{title}(続き)  |
| Table continuation: Figure x -- {title} (1/3) | 図 x-{title}(1/3) |
| Table continuation: Figure x (2/3) | 図 x(2/3) |
| Figure | 図 |
| Key | 記号説明 |
| Formula (Formula A.2) | 式 (式(A.2))|
| Where, | ここで，|
| Source (SOURCE: JIS Z 8101-2:2015, 1.1.4)| 出典 (出典:JIS Z 8101-2:2015 の 1.1.4)|
| Informative | 参考 |
| Normative | 規定 |
| Cross-references | -- |
| Subfigure reference: "Figure 2 a)" | 図 2 の a) |
| Note reference: 7.1 Note 2 | 7.1 の注記 2 |
| Clause 4 Example 2 | 箇条 4 の例 2 |
| B.2 Example 3 | B.2 の例 3 |
| Range reference: Clause 5 Note 1 to Note 3 | 箇条5の注1)~注3) |

## Terms and definitions boilerplate

Have terms no external source:
この規格で用いる主な用語及び定義は，次による。

No terms and no external source
この規格で用いる主な用語及び定義は，JIS X XXXX による。

Have terms with external source:
この規格で用いる主な用語及び定義は，次によるほか，JIS X XXXX による。

No terms and no source:
この規格には，定義する用語はない。

## Normative references boilerplate

No references:
この規格には，引用規格はない。

With references, mix of dated and undated references:
次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要 求事項を構成している。これらの引用規格のうち，西暦年を付記してあるものは，記載の年の版を適 用し，その後の改正版(追補を含む。)は適用しない。西暦年の付記がない引用規格は，その最新版(追 補を含む。)を適用する。

With references, all are dated references:
次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要 求事項を構成している。これらの引用規格は，記載の年の版を適用し，その後の改正版(追補を含む。) は適用しない。

With references, no dated reference:
次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要求事項 を構成している。これらの引用規格は，その最新版(追補を含む。)を適用する。

<img width="638" alt="Screenshot 2023-03-07 at 11 04 40 AM" src="https://user-images.githubusercontent.com/11865/223309741-fa4ab408-2122-4946-900d-b7cab0009a50.png">

## Bibliography boilerplate

(この規格で参照している規格など)
<img width="611" alt="Screenshot 2023-03-07 at 11 04 07 AM" src="https://user-images.githubusercontent.com/11865/223309644-b8917592-6c61-4d4f-b275-67c13b6013ce.png">

**Comment by ronaldtse** [comment]
Related to:
* https://github.com/metanorma/metanorma-iso/issues/948

**Comment by opoudjis** [comment]
> The requirements are stated in JIS Z 8301:2019, which is documented in (https://github.com/metanorma/mn-samples-jis/issues/1) .

I've Google Translated it, and in between that and informed guesses from ISO... Ugh..

**Comment by opoudjis** [comment]
Separate Word documents output for: Cover page, Biblio, Content body

**Comment by opoudjis** [comment]
Closing, relaton-jis is well-advanced.

**Comment by ronaldtse** [comment]
Also pubid-jis is completed.
