### ISSUE TITLE
Textual date representation

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#12]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

From cover page:
![image](https://user-images.githubusercontent.com/5559926/227897295-0da0d4d4-bf7b-4ebc-85bb-1abe1fdc3f44.png)

Currently:
- adoc:
```adoc
:published-date: 2019-07-22
```
- Presentation xml:
```xml
<date type="published">
<on>2019-07-22</on>
</date>
```

`令和元年` - Google translated is as `2019`
This sentence contains from two parts:
- `令和` means 'Reiwa era' https://en.wikipedia.org/wiki/Reiwa_era, from May 1, 2019
- `元年` means 'first year'
translate.ru (https://www.translate.ru/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D1%8F%D0%BF%D0%BE%D0%BD%D1%81%D0%BA%D0%B8%D0%B9-%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9?text=%E4%BB%A4%E5%92%8C%E5%85%83%E5%B9%B4) shows `The first year of Reiw`

Note: for `2019` - there are two  years in Japanese notation
![image](https://user-images.githubusercontent.com/5559926/227903501-6ec038ed-c0e0-47f5-b0fb-028828788edb.png)

(from https://groups.oist.jp/resource-center/japanese-year-converter)

`7 月22 日` - `July 22`

**Comment by ronaldtse** [comment]
Right now we don't have a good gem that works with Japanese dates. It would be easier if we just ask the user to input the dates for now.

**Comment by opoudjis** [comment]
> Right now we don't have a good gem that works with Japanese dates. 

https://github.com/twitter/twitter-cldr-rb does Japanese Gregorian dates fine: https://github.com/twitter/twitter-cldr-rb/blob/b5256d83cdb8e90310ab4a28994407b7139f8394/resources/locales/ja/calendars.yml . For Japanese Imperial eras, there likely are several gems out there (remember where Ruby originated), but we haven't searched for them yet.

**Comment by opoudjis** [comment]
https://github.com/RyoYamamotoJP/japanese_calendar

**Comment by opoudjis** [comment]
Yes, but only to the extent of customising Gregorian calendars. The Thai Buddhist calendar used to be supported, and was retracted; there is no indication of any Japanese imperial calendar.

**Comment by opoudjis** [comment]
I've used twitter_cldr to make the era year spelled out, the gem I've used is numeric.

**Comment by Intelligent2013** [comment]
@opoudjis thanks!

**Comment by opoudjis** [comment]
As you can see, @Intelligent2013, I am slowly catching up on very old backlog...
