### ISSUE TITLE
(URGENT) metanorma-jis gem not published at GitHub repository

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#122]
```sh
$ bundle
Fetching gem metadata from https://rubygems.pkg.github.com/metanorma/.
Could not find gem 'metanorma-jis' in rubygems repository https://rubygems.pkg.github.com/metanorma/
```

**Comment by ronaldtse** [comment]
Can we double check (and make a list of) all the private flavors so that they are published and up to date? Thanks.

**Comment by CAMOBAP** [comment]
To be on the same page where is this issue coming from?

As far as I see https://github.com/metanorma/metanorma-jis is a public repository, and it's published to rubygems.org

We have private nist and bsi and they successfully was pushed yesterday to https://rubygems.pkg.github.com/metanorma/

**Comment by ronaldtse** [comment]
Oh wow, I see... hmmm.

**Comment by CAMOBAP** [comment]
> Oh wow, I see... hmmm.

According to my understanding this may happens only if we have single `source "https://rubygems.pkg.github.com/metanorma"` in `Gemfile`, and `source "https://rubygems.org"` is missing

**Comment by ronaldtse** [comment]
Closing -- JIS is currently a public flavor...
