### ISSUE TITLE
Implement bibliographic sections in JIS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#125]
From https://github.com/metanorma/mn-samples-jis/issues/19

In JIS Z 8301 there are multiple bibliographical sections.

General (top-level bibliographic items, undifferentiated)
<img width="568" alt="Screenshot 2023-11-21 at 10 11 25 PM" src="https://github.com/metanorma/mn-samples-jis/assets/11865/87e15569-fafb-47b9-b316-b7997cb5d70e">

<img width="538" alt="Screenshot 2023-11-21 at 10 11 34 PM" src="https://github.com/metanorma/mn-samples-jis/assets/11865/8eaad760-4181-4ce1-81c9-03ba3a8b6f24">

<img width="541" alt="Screenshot 2023-11-21 at 10 12 39 PM" src="https://github.com/metanorma/mn-samples-jis/assets/11865/40bd81f0-a769-48a1-9aed-60ff30ced919">

These should technically be encoded as:
```adoc
[bibliography]
=== （略語）

* [[[JIS_X_0304,JIS X 0304]]], 国名コード

* [[[JIS_X_0412,JIS X 0412]]], （規格群）言語名コード

[bibliography]
=== （製図）

* [[[JIS_B_0601,JIS B 0601]]], 製品の幾何特性仕様（GPS） -- 表面性状：輪郭曲線方式 -- 用語, 定義及び表面性状パラメータ

* [[[JIS_Z_8310,JIS Z 8310]]], 製図総則

...
```

However, when these sections are encoded, the "undifferentiated bibliographic items" at the top gets displaced completely.

**Comment by opoudjis** [comment]
This is an issue throughout Metanorma, not just JIS: bibliographies are not assumed to have both bibliographic entries and subclauses.

**Comment by opoudjis** [comment]
If clause contains both bibitems and references, it needs to be kept as a `references` section and not a `clause`, in order to enable normative/non-normative status to be tagged.

This is messy, and if it becomes too messy, I may end up asking for a blank header instead.

**Comment by opoudjis** [comment]
This is a generic solution. We already support:

````
== biblio
=== biblio
=== biblio
==== biblio
````

We will now support

````
== biblio
* [[[w,x]]
* [[[y,z]]]
=== biblio
=== biblio
````

as equivalent to

````
== biblio
[unnumbered=true]
=== {blank}
* [[[w,x]]
* [[[y,z]]]
=== biblio
=== biblio
````

What else is there?
