### ISSUE TITLE
JIS Z 8301:2019 failure in cross-references

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-jis#126]
From https://github.com/metanorma/mn-samples-jis/issues/17#issuecomment-1821961087

# Description

Under certain circumstances that I haven't been able to identify, Metanorma is not recognizing certain cross-references even when they are correctly encoded.

Document JIS Z 8301:2019 from [mn-samples-jis](https://github.com/metanorma/mn-samples-jis) gives these errors:

```
No label has been processed for ID commentary-table-3
No label has been processed for ID commentary-table-4
No label has been processed for ID commentary-table-1
No label has been processed for ID commentary-table-2
No label has been processed for ID commentary-table-5
No label has been processed for ID fig1
No label has been processed for ID fig2
```

I have checked the encoding of these references and they are correct, but there is an issue with Metanorma not recognizing them.

# To reproduce

Compile JIS Z 8301:2019 from [mn-samples-jis](https://github.com/metanorma/mn-samples-jis)

**Comment by opoudjis** [comment]
The error is "hasn't assigned them an autonumber"; it means that, when Metanorma iterates through the document to assign autonumbers, it is missing these. Commentaries are a tacked-on addition for JIS, and Metanorma may not be iterating through them properly.

**Comment by opoudjis** [comment]
Not the error invoked here, but an error nonetheless:

Some crossreferences require containers to be formulated: so Notes have clause containers, meaning that the clause label needs to be prefixed to the Note label in crossreferences: Clause 4.2, Note 1.

In the case of commentaries, commentary subclauses are themselves referred to the commentary as a container: Commentary, Clause 1.

So any notes within commentary subclauses need to inherit their parent containers recursively: Commentary, Clause 1, Note 2.

**Comment by opoudjis** [comment]
Autonumbering of assets is done for annexes and for the main section of the text, but not for back material: bibliographies do not contain tables. In JIS, we deem the commentaries to be back material. That means that assets should be autonumbered in back material as well.

**Comment by opoudjis** [comment]
Despite the massive and necessary refactor... the issue is still happening in the source document. Resuming tomorrow.
