### ISSUE TITLE
Enable CodeClimate for this repo

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-jis#130]
For now https://codeclimate.com/github/metanorma/metanorma-jis is 404

**Comment by ronaldtse** [comment]
<img width="1109" alt="Screenshot 2024-10-17 at 8 18 50 PM" src="https://github.com/user-attachments/assets/898a0f3d-d126-4f02-a48a-37be1777cf4a">

It's available now. Closing. Thanks!
