### ISSUE TITLE
PDF JIS Z 8301: contributors table issues

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#14]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/227921486-bf658fb7-d80b-41c5-a929-0cda7bcf72df.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/227921545-074332c6-23da-478a-a941-fe2352a862a5.png)

To do:
- [x] remove `Contributors` from adoc (replace by `{blank}`}
- [x] set table unnumbered
- [x] set fixed columns width in adoc
- [x] remove borders in XSLT
- [x] set justify alignment
- [x] set center alignment for table header

**Comment by ronaldtse** [comment]
@Intelligent2013 the "justify alignment" is generally difficult at the PDF stage because the names are aligned (2-6 chars) according to surname / given name. We have to use the semantics of the surname / given name for alignment.

They can be arranged in the following patterns.

あ: surname
い: given name

```
あ　　　い
あ　　　い　い
あ　　　いいい
あ　あ　い
あ　あ　い　い
あ　あ　いいい
あああ　い
あああ　い　い
あああ　いいい
```

**Comment by Intelligent2013** [comment]
Metanorma supports 'Semantic spans' (https://www.metanorma.org/author/topics/document-format/text/#semantic-spans)

For adoc:
```
| (部会長) | span:surname[酒井]span:givenname[信介] | 横浜国立大学
```
presentation XML:
```xml
<td align="left" valign="top">
	<p id="_c2aedb4b-6b1a-25df-4ee8-f7815d019b9b">
		<span class="surname">酒井</span>
		<span class="givenname">信介</span>
	</p>
</td>
```

To do: 
- [ ] update adoc - add span tags for all rows
- [ ] update JIS XSLT - add spaces in `<span class="surname">` and `<span class="givenname">` in `clause[@type = 'contributors']/table`.

**Comment by Intelligent2013** [comment]
Done:
![image](https://github.com/metanorma/metanorma-jis/assets/5559926/0b8965a9-e242-4e61-a642-d1a502ae20dc)
