### ISSUE TITLE
Short docidentifier

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#18]
Source: https://github.com/metanorma/metanorma-jis/issues/9

The page header contains document number without `JIS`:
![image](https://user-images.githubusercontent.com/5559926/227948429-2b39b1a3-e7fd-41e9-abcd-36dad3608241.png)

Currently, these identifiers are available in the XML (I think `ISO` should be removed?):
```xml
		<docidentifier type="ISO">ISO JIS Z 8301:2019</docidentifier>
		<docidentifier type="iso-reference">ISO JIS Z 8301:2019()</docidentifier>
		<docidentifier type="URN">urn:iso:std:iso:JIS Z 8301:stage-60.60:ja</docidentifier>
		<docidentifier type="iso-undated">ISO JIS Z 8301</docidentifier>
		<docidentifier type="iso-with-lang">ISO JIS Z 8301:2019(ja)</docidentifier>
		<docnumber>JIS Z 8301</docnumber>
```

Please add the `docidentifier` without `JIS` prefix.

**Comment by ronaldtse** [comment]
Correct, these identifiers should have their types changed to "jis", and the "ISO" prefix removed.

This can be done together with #8 .

The URN is also incorrect, thought there is no JIS URN.

**Comment by opoudjis** [comment]
This has already been done in latest release.

````
      :docnumber: 1000
      :docseries: Z
````

````
           <docidentifier type="JIS">JIS Z 1000:2000</docidentifier>
           <docnumber>1000</docnumber>
````

**Comment by Intelligent2013** [comment]
From the initial post:

> Please add the `docidentifier` without `JIS` prefix.

ping @opoudjis

**Comment by opoudjis** [comment]
````
           <docidentifier type="JIS">Z 1000:2000</docidentifier>
           <docnumber>1000</docnumber>
````

````
           <docidentifier type="JIS">TR Z 1000:2023</docidentifier>
           <docnumber>1000</docnumber>
````
