### ISSUE TITLE
Bibliography: listed non-standards that have URLs always render the URLs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#194]
The JIS bilbiography is currently devoid of all links.

This seems to be a bug.

Proper JIS rendering of the bibliography always includes the URL:

<img width="332" alt="image" src="https://github.com/user-attachments/assets/9323cefe-466d-4fcb-8da5-3bf588683a54">

<img width="340" alt="image" src="https://github.com/user-attachments/assets/50ed13d6-82a4-40b3-b797-db8b683ad8a8">

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-plateau/issues/112#issuecomment-2230217706_

**Comment by opoudjis** [comment]
Fixed in https://github.com/metanorma/mn-samples-plateau/issues/112

**Comment by opoudjis** [comment]
JIS and thus Plateau use the default Relaton Render template. In this instance, with no doctype defined on the reference, they are rendered with  the misc template, which has not until now provided for URLs.

**Comment by opoudjis** [comment]
![Screenshot 2024-07-19 at 01 40 19](https://github.com/user-attachments/assets/c398528a-f0f9-4ba7-91f0-831801f4cdfe)
