### ISSUE TITLE
PDF JIS Z 8301: encode references

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#21]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

Original PDF - standard's identifier in bold:
![image](https://user-images.githubusercontent.com/5559926/227967558-58315051-d7f6-4da4-bd18-6595e113cf05.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/227967669-f7713c3c-d628-4857-9fa5-6bfb535221f0.png)

To do: 
- [x] encode the standard's reference as https://www.metanorma.org/author/topics/document-format/bibliography/#link-only-references:
```adoc
std-link:[JIS Z 8301:2011]
```
- [x] render doc identifier in bold and colon with year in non-bold

**Comment by ronaldtse** [comment]
@Intelligent2013 I believe all these cross-references should technically be bibliographic items? It would be better to encode them as bibliographic entries rather than `std-links`.

**Comment by Intelligent2013** [comment]
@ronaldtse some bibliographic items are missing in the Bibliography section in the original PDF.
For instance, `JIS Z 8301:2011` (may be because this is the same document, but earlier, and there aren't years in Bibliography section....).
If we encode them as bibliographic entries, the we'll see them in the Bibliography. It's ok?

**Comment by ronaldtse** [comment]
> For instance, JIS Z 8301:2011 (may be because this is the same document, but earlier, and there aren't years in Bibliography section....).

This can be encoded as a hidden ref as:
```adoc
* [[[jis_z_8301_2011,hidden(JIS Z 8301:2011)]]]
```

> If we encode them as bibliographic entries, the we'll see them in the Bibliography. It's ok?

We can use the `hidden(...)` syntax to hide them.

**Comment by ronaldtse** [comment]
Of course the other option is just to use `std-link:[xxx]`. This might be the best choice. Let's do that.

**Comment by Intelligent2013** [comment]
I think in the examples we should encode references just as the bold text, not as the bibliographic references.
```
[example]
これらコネクタの接続では，*JIS C 3662-3* に規定されたケーブルの配線及
びケーブルの直径を考慮することが望ましい。
```

**Comment by ronaldtse** [comment]
Agree.

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/228626693-7ef9bf41-d6b2-4a3a-8489-17396cc22346.png)
