### ISSUE TITLE
PDF JIS Z 8301: different text in Normative References

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#23]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/228020586-67022fdb-7e5c-40bc-8c32-5a2e6c71e08c.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/228020647-2d92d6d6-774a-4533-883b-b8b5d16bd298.png)

**Comment by Intelligent2013** [comment]
From `15.5.2.1 前置き文`:

![image](https://user-images.githubusercontent.com/5559926/235504891-28c2ad2a-dda7-4e65-8fc2-eb0120cd8060.png)

Text:
```
引用規格の箇条では，前置き文として，通常，次のいずれかの定型文を用いる。
a) 全ての引用規格に西暦年の付記がない場合
“次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要
求事項を構成している。これらの引用規格は，その最新版（追補を含む。）を適用する。”
b) 全ての引用規格に，西暦年の付記がある場合と西暦年の付記がない場合とが混在している場合
“次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要
求事項を構成している。これらの引用規格のうち，西暦年を付記してあるものは，記載の年の版を適
用し，その後の改正版（追補を含む。）は適用しない。西暦年の付記がない引用規格は，その最新版（追
補を含む。）を適用する。”
c) 全ての引用規格に西暦年の付記がある場合
“次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要
求事項を構成している。これらの引用規格は，記載の年の版を適用し，その後の改正版（追補を含む。）
は適用しない。”
d) 引用規格がない場合
“この規格には，引用規格はない。”
```

In the original PDF the variant `a)` used, but in the Presentation XML (and generated PDF) - `b)`.

Translation:
`a) When there is no year notation in all cited standards`
`b) When all cited standards have a mixture of years with and without year additions`


All items in the `02-norm_refs.adoc` encoded without year:
```
[bibliography]
[heading=Normative references]
== 引用規格

* [[[JIS_B_0001,JIS B 0001]]], 機械製図

* [[[JIS_B_0060,JIS B 0060]]],（規格群） デジタル製品技術文書情報

* [[[JIS_C_0450,JIS C 0450]]], 電気及び関連分野－信号指定及び接続指定

* [[[JIS_C_0617,JIS C 0617]]],（規格群） 電気用図記号

* [[[JIS_P_0138,JIS P 0138]]], 紙加工仕上寸法
```
but Presentation XML (and PDF) contains year:
![image](https://user-images.githubusercontent.com/5559926/235506009-f63bd63c-a505-4237-aca8-da04dc9c3936.png)

I'll try to add the rendered text in `(...)`:
```
* [[[JIS_B_0001,(JIS B 0001)JIS B 0001]]], 機械製図
```

**Comment by Intelligent2013** [comment]
For one reference:
```adoc

[bibliography]
[heading=Normative references]
== 引用規格

* [[[JIS_B_0001,(JIS B 0001)JIS B 0001]]], 機械製図
```

Presentation XML contains the text:
```
次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要 求事項を構成している。これらの引用規格は，記載の年の版を適用し，その後の改正版(追補を含む。) は適用しない。
```
looks like from `norm_with_refs_pref_none_dated` (`i18n-ja.yaml`):
```
norm_with_refs_pref_all_dated: 次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要 求事項を構成している。これらの引用規格は，記載の年の版を適用し，その後の改正版(追補を含む。) は適用しない。
norm_with_refs_pref_none_dated: 次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要求事項 を構成している。これらの引用規格は，その最新版(追補を含む。)を適用する。
```

but for adoc:
```adoc

[bibliography]
[heading=Normative references]
== 引用規格

* [[[JIS_B_0001,(JIS B 0001)JIS B 0001]]], 機械製図

* [[[JIS_B_0060,(JIS B 0060)JIS B 0060]]],（規格群） デジタル製品技術文書情報

* [[[JIS_C_0450,(JIS C 0450)JIS C 0450]]], 電気及び関連分野－信号指定及び接続指定

* [[[JIS_C_0617,(JIS C 0617)JIS C 0617]]],（規格群） 電気用図記号

* [[[JIS_P_0138,(JIS P 0138)JIS P 0138]]], 紙加工仕上寸法
```

Presentation XML contains:
```
次に掲げる引用規格は，この規格に引用されることによって，その一部又は全部がこの規格の要 求事項を構成している。これらの引用規格のうち，西暦年を付記してあるものは，記載の年の版を適 用し，その後の改正版(追補を含む。)は適用しない。西暦年の付記がない引用規格は，その最新版(追 補を含む。)を適用する。
```
from `norm_with_refs_pref_all_dated` + additional text `西暦年の付記がない引用規格は，その最新版(追 補を含む。)を適用する`.

I don't understand at all how it's working.
ping @opoudjis.

**Comment by opoudjis** [comment]
Your error is:

> All items in the 02-norm_refs.adoc encoded without year:

That is utterly irrelevant. What matters is what is FETCHED BACK from relaton. What is fetched back from relaton has a year: as you can see, JIS B 0001 fetches back JIS B 0001:2019. Therefore, as far as Metanorma-JIS is concerned, that citation has a year.

So the real issue is, whether relaton-jis is acting correctly, in returning a year-specific citation. It isn't, of course, and it needs to behave the same way as relaton-iso does, in returning an undated year, with the year specific instance as a related entry. Raising issue with Andrej.

**Comment by opoudjis** [comment]
Now generating with:

````
<references id="___x5f15___x7528___x898f___x683c_" normative="true" obligation="informative">
<title>引用規格</title><p id="_fea7f834-8928-2189-bca9-6eb94632c528">次に掲げる引用規格は，この規格に引用されることによって，その一部又>は全部がこの規格の要求事項 を構成している。これらの引用規格は，その最新版(追補を含む。)を適用する。</p>
````
