### ISSUE TITLE
Error: loading gem `metanorma-jis` failed.

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#233]
I'm trying to generate the presentation XML the document for https://github.com/metanorma/mn-samples-jis/tree/main/sources/jis-z-8301-2019.

`bundle exec metanorma -t jis -x presentation document.adoc`:
```
[metanorma] Error: loading gem `metanorma-jis` failed. Exiting.

Troubleshooting:
1. If you are using metanorma via bundler/ruby, make sure that your
   Gemfile contains a line:
     gem "metanorma-jis"

2. If you are using brew/choco/snap packages, please report an issue
   to https://github.com/metanorma/packed-mn/issues/new"
```
I've tried to add `gem "metanorma-jis"` into `Gemfile`, then again `bundle update`, the same error.
I don't figure out what's happened.

**Comment by Intelligent2013** [comment]
From `Gemfile.lock`:
```
    metanorma-jis (0.3.6)
      japanese_calendar (~> 0)
      metanorma-iso (~> 2.8.0)
      pubid
```

`gem which metanorma-jis`:
```
C:/Users/TestUser/.local/share/gem/ruby/3.3.0/gems/metanorma-jis-0.3.6/lib/metanorma-jis.rb
```

**Comment by opoudjis** [comment]
Cannot replicate: same Gemfile.lock as you, and it's compiling fine.

**Comment by Intelligent2013** [comment]
After the _full uninstall_ and install of `ruby`, `msys2` and `metanorma` via chocolatey the issue was gone.
