### ISSUE TITLE
Table name in the table header

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#24]
Source document: https://github.com/metanorma/mn-samples-jis/tree/main/sources/jis-z-8301-2019

From `00-preface.adoc`:
```adoc
[.preface,type=contributors]
== Contributors

.日本産業標準調査会標準第一部会 構成表
|===
| | 氏名 | 所属
```

Metanorma presentation XML - table's name moved into the 1st header row:
```xml
<clause id="_contributors" type="contributors" inline-header="false" obligation="informative" displayorder="3">
	<title depth="1">Contributors</title>
	<table id="_">
		<thead>
			<tr>
				<td border="0" colspan="3">
					<p class="TableTitle" style="text-align:center;">表 1 — 日本産業標準調査会標準第一部会 構成表</p>
				</td>
			</tr>
			<tr>
				<th valign="top" align="left"/>
				<th valign="top" align="left">氏名</th>
				<th valign="top" align="left">所属</th>
			</tr>
		</thead>
		<tbody>
			<tr>
...
```

Expected XML:
```xml
	<table id="_">
		<name>表 1 — 日本産業標準調査会標準第一部会 構成表</name>
		<thead>
			<tr>
				<th valign="top" align="left"/>
				<th valign="top" align="left">氏名</th>
				<th valign="top" align="left">所属</th>
			</tr>
		</thead>
		<tbody>
			<tr>
```

**Comment by ronaldtse** [comment]
Maybe we should re-encode this as a definition list, with "author" and "affiliation" separate?

**Comment by Intelligent2013** [comment]
@ronaldtse the original table has 3 columns, and header:
![image](https://user-images.githubusercontent.com/5559926/228137180-f5fd2712-5c31-40eb-b7c7-16eeefad049c.png)

I don't figure out how to encode it as one semantic unit with using of definition list (2 column table).

**Comment by ronaldtse** [comment]
Original content:
```adoc
.日本產業標準調查会標準第一部会 □□技術專門委員会 (organization group name) 構成表 (members)
|===
| | 氏名 (name) | 所属 (affiliation)

| (委員会長) (this is the position in the organization group) | □□□□ | □□大学

| (委員)      | 伊藤弘 | 国立研究開発法人建築研究所
| | □□□□ | 国立研究開発法人□□□□□□研究所
| | □□□□ | □□□□省□□□□□□局
...
```

So the definition list can look like this:

```adoc
group:: 日本產業標準調查会標準第一部会 □□技術專門委員会 (organization group name)
name::: □□□□
position::: 委員会長
affiliation::: □□大学
name::: 伊藤弘
position::: 委員
affiliation::: 国立研究開発法人建築研究所
name::: □□□□
position::: 委員
affiliation::: 国立研究開発法人□□□□□□研究所
name::: □□□□
position::: 委員
affiliation::: □□□□省□□□□□□局
```

Notice all the 委員 are grouped together with only the first row showing the position name.

**Comment by Intelligent2013** [comment]
Additional issue with empty `thead` from https://github.com/metanorma/metanorma-jis/issues/76#issuecomment-1534522249:
For source adoc:
```adoc
====
[%unnumbered]
image::fig_29.5.1_example.png[]

[cols="^.^,^.^,^.^,^.^,^.^,^.^",options="unnumbered"]
|===
.2+h| 呼び
4+h| 寸法
.2+h| 質量（参考） +
（kg）

.<| stem:[d_1] .<| stem:[d_2] .>| stem:[l_1] .>| stem:[l_2]
| S | 25 .2+| 10 | 120 | 100 | 4.5
| T | 31.5 | 145 | 125 | 5.6
| U | 40 .2+| 20 | 180 | 160 | 7.1
| V | 50 .2+| 220 .2+| 200 | 9.0
| W | 63 | 40 | 11.2

|===
====
```

the Presentation XML contains empty `thead`:
```xml
<table id="_42e1f550-704c-9531-9050-db05b902a9fa" unnumbered="true">
	<thead> </thead>
	<tbody>
		<tr>
			<th valign="middle" rowspan="2" align="center">呼び</th>
			<th colspan="4" valign="middle" align="center">寸法</th>
			<th valign="middle" rowspan="2" align="center">質量（参考）<br/>
```

**Comment by opoudjis** [comment]
To start with:

The semantic XML is:

````
<table id="_67a81fc1-0913-4be7-a070-7e7ecb82432c">
<name>日本産業標準調査会標準第一部会 構成表</name>
<tbody><tr><td valign="top" align="left"/><td valign="top" align="left">氏名</td>
<td valign="top" align="left">所属</td>
</tr></tbody>
</table>
````


The fact that the name has been moved into thead is deliberate, because that is how JIS does tables in the example document. 

![Screenshot 2024-02-22 at 01 05 20](https://github.com/metanorma/metanorma-jis/assets/1911039/b6649569-f0bb-4115-a02f-3c7c29cef64b)



(In fact, JIS represent tables in Word as tables nested within tables. Which is nothing but insane.)

With no guidance on rendering provided by JIS other than a very badly designed document, I am not inclined to revisit this design decision. OTOH, I am willing to change this so that this moving of titles into the thead should happen in Word rendering and not as early as Presentation XML: this is a presentation requirement, but I can see it isn't really a PDF requirement.

@ronaldtse I think encoding participants semantically is way premature, given the nonsensically little information or support that metanorma-jis has received to date. I'm not going waste effort coding stuff that will be annulled when or if JIS get around to providing more substantive information.

**Comment by opoudjis** [comment]
> Wrong Presentation XML - empty `<thead> </thead>`:
> 
> ```
> <table id="_42e1f550-704c-9531-9050-db05b902a9fa" unnumbered="true">
> 	<thead> </thead>
> 	<tbody>
> 		<tr>
> 			<th valign="middle" rowspan="2" align="center">呼び</th>
> 			<th colspan="4" valign="middle" align="center">寸法</th>
> 			<th valign="middle" rowspan="2" align="center">質量（参考）<br/>
> ```
> 
> There XSL-FO is wrong also:
> 
> ```
> <fo:table-header> </fo:table-header>
> ```
> 
> Source adoc:
> 
> ```
> ====
> [%unnumbered]
> image::fig_29.5.1_example.png[]
> 
> [cols="^.^,^.^,^.^,^.^,^.^,^.^",options="unnumbered"]
> |===
> .2+h| 呼び
> 4+h| 寸法
> .2+h| 質量（参考） +
> （kg）
> 
> .<| stem:[d_1] .<| stem:[d_2] .>| stem:[l_1] .>| stem:[l_2]
> | S | 25 .2+| 10 | 120 | 100 | 4.5
> | T | 31.5 | 145 | 125 | 5.6
> | U | 40 .2+| 20 | 180 | 160 | 7.1
> | V | 50 .2+| 220 .2+| 200 | 9.0
> | W | 63 | 40 | 11.2
> 
> |===
> ====
> ```
> 
> I assume that this issue relates to the #24 This table is without title and `unnumbered`, therefore we get empty `thead`.
> 
> ping @opoudjis

This is a markup issue:

Asciidoctor natively cannot deal with more than one header row.

This table has rowspans in its first row. That means it has more than one header row, and Asciidoctor cannot deal with that.

The resolution to that, which I introduced in Metanorma, is to add the attribute `headerrows=2` to that table:

````
====
[%unnumbered]
image::fig_29.5.1_example.png[]

[headerrows=2,cols="^.^,^.^,^.^,^.^,^.^,^.^",options="unnumbered"]
|===
.2+h| 呼び
4+h| 寸法
.2+h| 質量（参考） +
（kg）

.<| stem:[d_1] .<| stem:[d_2] .>| stem:[l_1] .>| stem:[l_2]
| S | 25 .2+| 10 | 120 | 100 | 4.5
| T | 31.5 | 145 | 125 | 5.6
| U | 40 .2+| 20 | 180 | 160 | 7.1
| V | 50 .2+| 220 .2+| 200 | 9.0
| W | 63 | 40 | 11.2

|===
====
````

**Comment by opoudjis** [comment]
Moving name into thead only for HTML, DOC, and not in Presentation XML. Not actioning further at this time.
