### ISSUE TITLE
Participants encoding as document attributes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-jis#249]
@manuelfuenmayor has queried me how to encode participants as document attributes, based on 

https://www.metanorma.org/author/jis/ref/document-attributes/#organization-contributors

and 

![image](https://github.com/user-attachments/assets/8d0f2605-6041-47cf-b6da-d30aaf08a302)

Now, although it is not well documented, because it involves attributes in standoc not included in that page, it is possible to represent that information using just document attributes:

````
:investigative-committee: JSA-S1020 Working Group
:fullname: Hiroki Yamakawa
:role: authorizer
:role-description: investigative committee
:affiliation: Manager, Learning solutions Department, Sales Division, UCHIDA HUMAN DEVELOPMENT CO., LTD
:contributor-position: Project General Manager
:fullname_2: Takefumi Omote
:role_2: authorizer
:role-description_2: investigative committee
:affiliation_2: General Manager, Learning Solutions Department, Panasonic Solution Technologies CO., Ltd
:contributor-position_2: Vice Project Manager
:fullname_3: Katsuya Matsuda
:role_3: authorizer
:role-description_3: investigative committee
:contributor-position_3: Vice Project Manager
:affiliation_3: Director, HRD Innovation Division, Knowledge Services Unit, FUJITSU LEARNING MEDIA LIMITED
:fullname_4: Michiko Arima
:role_4: authorizer
:role-description_4: investigative committee
:affiliation_4: Department Manager, Quality Assurance Center, Learning Service Division, Hitachi Academy Co., Ltd.
:contributor-position_4: Member
:fullname_5: Toru Ishiyama
:role_5: authorizer
:role-description_5: investigative committee
:affiliation_5: Manager, HRD Services Division, NEC Management Partner, Ltd.
:contributor-position_5: Member
:fullname_6: Nobuyuki Yagi
:role_6: authorizer
:role-description_6: investigative committee
:affiliation_6: President, JAMOTE Certification Services Co., Ltd.
:contributor-position_6: Observer
````

As it turns out, though, we have not used that representation at all. Instead, we have used participant clauses: https://www.metanorma.org/author/jis/topics/markup/#participant-clauses

````
[type=participants]
== {blank}

[source,yaml]
----
- name: Hiroki Yamakawa
  affiliation: Manager, Learning solutions Department, Sales Division, UCHIDA HUMAN DEVELOPMENT CO., LTD
  role: Project General Manager
- name: Takefumi Omote
  affiliation: General Manager, Learning Solutions Department, Panasonic Solution Technologies CO., Ltd
  role: Vice Project Manager
- name: Katsuya Matsuda
  affiliation: Director, HRD Innovation Division, Knowledge Services Unit, FUJITSU LEARNING MEDIA LIMITED
  role: Vice Project Manager
- name: Michiko Arima
  affiliation: Department Manager, Quality Assurance Center, Learning Service Division, Hitachi Academy Co., Ltd.
  role: Member
- name: Toru Ishiyama
  affiliation: Manager, HRD Services Division, NEC Management Partner, Ltd.
  role: Member
- name: Nobuyuki Yagi
  affiliation: President, JAMOTE Certification Services Co., Ltd.
  role: Observer
----
````

This renders as:

![Screenshot 2024-11-25 at 22 23 13](https://github.com/user-attachments/assets/45efb011-75b7-4986-8ab8-673b3e67f0fc)

This ticket is for:

* Supporting the document attribute markup of JIS committees instead of participant clauses. I am not enthusiastic about that prospect.
* Making the roles cells span multiple rows if they repeat. I am not enthusiastic about that either.

@manuelfuenmayor You can proceed with markup using participant clauses instead now.

**Comment by manuelfuenmayor** [comment]
Thanks, Nick. I've obtained the same result as you with the participant clauses approach.

However, the [document ](https://github.com/metanorma/mn-samples-jis/blob/main/reference-docs/jsa-s_01020_000_000_2022_e_ed10_ch.pdf)actually displays two tables: "JSA-S1020 Drafting Committee" and "JSA-S1020 Working Group."

The participant clauses markup results in one table, though.

## Tables

<img src="https://github.com/user-attachments/assets/fa9924ba-3c42-4f5a-8522-8638810844aa" width="700" height="500">

<img src="https://github.com/user-attachments/assets/688da609-54c9-4c73-8041-347c41b88422" width="700" height="500">

**Comment by opoudjis** [comment]
Yes, I clearly only ever anticipated one of these being needed. Promoted to Urgent, but am still unlikely to get to it for a couple of weeks.

**Comment by opoudjis** [comment]
Refer https://github.com/metanorma/mn-samples-jis/pull/54#issue-2718757161

**Comment by opoudjis** [comment]
In order to allow more than one table, we need to allow captions on participant tables, instead of copying their title from the working group.

**Comment by opoudjis** [comment]
it is adhoccery, but I'll allow for a key at the bottom of the participant clause, encoded as with other keys, as 

````
[%key]
PL:: Whatever PL stands for
TPM:: Whatever TPM stands for
````

**Comment by opoudjis** [comment]
@anermina @manuelfuenmayor Please review whether this will work for you. The encoding changes to:

````
[type=participants]
== Explicit title of participant clause, rather than default given by working group

[source,yaml]
----
the yaml you already have
----

[%key]
Definition list giving:: definitions of abbreviations used in the yaml
````

**Comment by ReesePlews** [comment]
> [%key]
> PL:: Whatever PL stands for
> TPM:: Whatever TPM stands for

hi Nick, i am assuming in this context that PL is project leader, TPM is Technical Programme Manager

**Comment by manuelfuenmayor** [comment]
> Please review whether this will work for you.

Yes, the rendering is correct now. Thanks, Nick!
