### ISSUE TITLE
Vertical layout: Automatic detection of document language and script

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#255]
Source issue: https://github.com/metanorma/metanorma-jis/issues/226

From https://github.com/metanorma/docs/blob/main/109.adoc:

> Metanorma implements vertical layout support through:
> * Automatic detection of document language and script

@ronaldtse currently, the vertical layout for JIS documents applies when `:presentation-metadata-vertical-layout: true` is set.  This contradicts the statement above. Would you like to apply the vertical layout automatically by the attribute `:language: ja`? Then, how to apply the horizontal layout - when `:presentation-metadata-vertical-layout: false` is set?

**Comment by ronaldtse** [comment]
@Intelligent2013 the current setup is good! We should change 109 to indicate that the default type of layout applied depends on the flavor and document type. Right now default JIS is still horizontal.

**Comment by Intelligent2013** [comment]
@ronaldtse could you add the write permission to `docs` repository. I'm trying to push, but:
```
remote: Permission to metanorma/docs.git denied to Intelligent2013.
fatal: unable to access 'https://github.com/metanorma/docs/': The requested URL returned error: 403
```
Thank you.

**Comment by ronaldtse** [comment]
> @ronaldtse could you add the write permission to `docs` repository. I'm trying to push, but:
> 
> ```
> remote: Permission to metanorma/docs.git denied to Intelligent2013.
> fatal: unable to access 'https://github.com/metanorma/docs/': The requested URL returned error: 403
> ```
> 
> Thank you.

Done!
