### ISSUE TITLE
Vertical layout: keep multi-digit numbers in horizontal orientation

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#257]
Source issue: https://github.com/metanorma/metanorma-jis/issues/226

From https://github.com/metanorma/docs/blob/main/109.adoc:

> ===== Numerical content
> For numerical content in vertical text, the renderer shall:
> 
> * Keep multi-digit numbers in horizontal orientation

Current implementation doesn't not realized this requirement automatically:
![image](https://github.com/user-attachments/assets/d2dc9781-5a36-49be-84ae-11800d8000c3)

The task is do it automatically.

Currently, we have to enclose each such characters sentence into the markup `span:horizontal:[...]`. In this case, the sentence of 2-3 digits looks ok, but 4 or more digits render to close the neighboring columns (see `8301` and `2011`): 

![image](https://github.com/user-attachments/assets/0e25f09f-d5bd-4e0d-b512-ec48fec888d1)

There are different practices to show the Arabic numbers in the vertical writing.

In the article [How to write numbers in Japanese – Vertical writing and horizontal writing](https://kanji.tools/column/how-to-write-numbers-in-japanese-vertical-writing-and-horizontal-writing/) said:
> First of all, the way of writing numbers is different in vertical writing and horizontal writing.
> When you write Japanese horizontally, basically, Arabic numerals are used.
> Kanji for numbers (漢数字, Kansūji) is basically for vertical writing.

The sample `787` in the vertical orientation: https://kanji.tools/column/how-to-write-numbers-in-japanese-vertical-writing-and-horizontal-writing/#vertical_sample_img:
![image](https://github.com/user-attachments/assets/5c543d7a-fae4-4cb3-b7af-58df6b5b41d9)

In the article [Styling vertical Chinese, Japanese, Korean and Mongolian text](https://www.w3.org/International/articles/vertical-text/#tcy) there are a few examples how to represent horizontal in vertical:
> It is common for short numbers of 2-3 digits (sometimes 4) and occasionally other runs of text, to run horizontally within the vertical flow. In Japanese this is called tate chū yoko. See the month and day digits in this example.
> ![image](https://github.com/user-attachments/assets/bfe9cd85-133e-41a4-bf37-468d28d1522c)
> ...
> ![image](https://github.com/user-attachments/assets/4d3574e9-882d-4c2d-9d54-221803300795)

Note: I don't sure that this squeeze effect can be achieved in XSL-FO.

> ...
> ![image](https://github.com/user-attachments/assets/8f713bf5-eb1d-411e-97e1-53133251b856)

Also, the different practices specified in

[Major Differences between Vertical Writing Mode and Horizontal Writing Mode](https://www.w3.org/TR/jlreq/?lang=en#major_differences_between_vertical_writing_mode_and_horizontal_writing_mode)
 
[Mixed Text Composition in Vertical Writing Mode](https://www.w3.org/TR/jlreq/?lang=en#mixed_text_composition_in_vertical_writing_mode)

The topic is very wide...

Regarding the requirement 'keep multi-digit numbers in horizontal orientation', I propose to limit the count of digits to 3. If sentence of digits more than 3 digits, then render it in the vertical mode one by one.

@ronaldtse any thoughts?

**Comment by ReesePlews** [comment]
fascinating discussions here. the W3C resource is quite comprehensive and modern. the only other CJK resource i know of in english is the Ken Lunde book CJKV Information Processing: Chinese, Japanese, Korean, and Vietnamese Computing, but it is from 2009. but i am sure there are other native language sources that i am not aware of.  sorry i cannot contribute much to this, but again, a really interesting discussion.

**Comment by Intelligent2013** [comment]
JIS XSLT updated for bibliographic numbers rendering in the horizontal orientation:
![image](https://github.com/user-attachments/assets/bd00e11f-badb-4df6-b86a-d6144c10bf2b)

![image](https://github.com/user-attachments/assets/747cba46-34a2-4f00-9629-1b9b613ce870)

**Comment by Intelligent2013** [comment]
Currently, 2-3 digits sequence renders in the horizontal orientation.
Closing issue.
If need more improvements, lets re-open this issue.
