### ISSUE TITLE
Word: standard name (Japanese, English) on first body page uses wrong style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#27]
Now:
<img width="1109" alt="Screenshot 2023-03-28 at 1 38 15 PM" src="https://user-images.githubusercontent.com/11865/228138668-ad89fd3a-a011-4897-a441-f26c1af6de7b.png">

The correct style is: "規格名称"

<img width="1056" alt="Screenshot 2023-03-28 at 1 38 43 PM" src="https://user-images.githubusercontent.com/11865/228138757-265c7770-1469-4cc0-8038-9e521a859459.png">

The English style is also wrong:
<img width="959" alt="Screenshot 2023-03-28 at 1 39 02 PM" src="https://user-images.githubusercontent.com/11865/228138811-65a2a031-fd12-4fe4-9a1c-3a8610e8dccb.png">

It should be "規格名称（英語）". However, I think this style has been corrupted.

From an old TR, the style is this:
<img width="748" alt="Screenshot 2023-03-28 at 1 41 32 PM" src="https://user-images.githubusercontent.com/11865/228139255-834abc9e-06ec-470f-aa2a-823daf943284.png">

From the Metanorma-generated document, the style looks like this:
<img width="748" alt="Screenshot 2023-03-28 at 1 42 06 PM" src="https://user-images.githubusercontent.com/11865/228139346-9af779b7-15a6-4b28-a1ee-ee6de18f814b.png">

The current style is likely wrong.

**Comment by ronaldtse** [comment]
Another comparison of new vs old styles (left and right):
<img width="594" alt="Screenshot 2023-03-28 at 1 42 42 PM" src="https://user-images.githubusercontent.com/11865/228139501-0c2d8019-c2a0-4b11-8c6c-a2a7e65dfb6f.png">

**Comment by opoudjis** [comment]
Japanese standard name has already been fixed.

English standard name was fixed, but name was left ambiguous: fixed.
