### ISSUE TITLE
Implement commentary

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#28]
In JIS documents there is often a "Commentary" section that goes after the Bibliography.

It has the following attributes:
<img width="600" alt="Screenshot 2023-03-28 at 1 51 29 PM" src="https://user-images.githubusercontent.com/11865/228142562-3d3d3096-1437-46fe-80b8-f1e607601696.png">
<img width="608" alt="Screenshot 2023-03-28 at 1 59 53 PM" src="https://user-images.githubusercontent.com/11865/228142589-87868aa7-e979-4e97-bebd-481f5efb50ee.png">

**Comment by opoudjis** [comment]
I am not going to introduce a new Semantic XML tag for commentaries, because I am not indulging every flavour in its insanity.

Commentaries shall be annexes, of type commentary, marked up as:

`[appendix%commentary]`

I will move these in the Presentation XML to after the bibliography.

**Comment by ronaldtse** [comment]
@opoudjis we have now seen a number of commentaries: BSI (published separately), JIS (published inside of document or separately). It is possibly worthwhile implementing proper support for it.

**Comment by opoudjis** [comment]
We have seen two, and in BSI, it is a completely distinct document type. That means we have seen all of one.

Annexes are any subsidiary material added to the main body of a document. That is a simple, clean, consistent definition, and it includes commentaries, code tables, correspondence, and usage guides. Not indulging SDOs in *Semantic* XML in what they choose to call that subsidiary material is not "implementing proper support for it", it is making a clean document model hostage to SDO whims. And it will not happen on my watch.

**Comment by opoudjis** [comment]
Almost complete. To go: numbering of sub-clauses of commentaries but not commentaries themselves as annexes; page numbering and heading in Word for commentaries as part of a distinct section.

**Comment by opoudjis** [comment]
You're requesting that Word display both the overall page count, and the page count of just the current section. I'm not convinced Word is doing that at all; I can only get it to do one or the other.

**Comment by opoudjis** [comment]
... I've copied the header across, and it's not working; my very strong suspicion is that this functionality is not supported in DOC at all. Then again, it's not working correctly in the sample document of 5999 in DOCX either (it's frozen on "Comm. 2) every second page of the commentary), and my very strong suspicion is that it's manually set by JIS. Will not fix, we would need to see a working example, and I am not convinced this genuinely is Word functionality to begin with.

**Comment by ronaldtse** [comment]
> ... I've copied the header across, and it's not working; my very strong suspicion is that this functionality is not supported in DOC at all. Then again, it's not working correctly in the sample document of 5999 in DOCX either (it's frozen on "Comm. 2" as the page number every second page of the commentary), and my very strong suspicion is that it's manually set by JIS. Will not fix, we would need to see a working example, and I am not convinced this genuinely is Word functionality to begin with.

Please see this for a the Commentary having separate page numbers:
* https://github.com/metanorma/mn-samples-jis/tree/main/reference-docs/TR-X-0067-2002
