### ISSUE TITLE
PDF output for JIS

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-jis#3]
From https://github.com/metanorma/metanorma-jis/issues/1

Word sample document in https://github.com/metanorma/jis-example-report/issues/1

**Comment by ronaldtse** [comment]
@Intelligent2013 please use the layout defined in JIS Z 8301, not the same document.

**Comment by Intelligent2013** [comment]
For:
`00-foreword.adoc`:
```adoc
[heading=foreword]
== まえがき
...
```
`00-preface.adoc`:
```adoc
[.preface,type=inner-cover-note]
== Inner cover note
...
[.preface,type=contributors]
== Contributors
```

presentation XML looks ok:
```xml
<preface>
	<foreword id="_" obligation="informative" displayorder="1">
		<title>まえがき</title>
...
	<clause id="_inner_cover_note" type="inner-cover-note" inline-header="false" obligation="informative" displayorder="2">
		<title depth="1">Inner cover note</title>
...
	<clause id="_contributors" type="contributors" inline-header="false" obligation="informative" displayorder="3">
		<title depth="1">Contributors</title>
```


@ronaldtse can we change the roles `[.inner-cover-note]` `[.contributors]` to the preface types `[.preface,type=inner-cover-note]` and `[.preface,type=contributors]` or it did specially?

**Comment by ronaldtse** [comment]
@Intelligent2013 sure, let's do that. Thanks.

**Comment by Intelligent2013** [comment]
The order of the preface sections:
- `preface/clause[@type = 'contributors']`
- `preface/clause[@type = 'inner-cover-note']` at page bottom
- page break
- ToC
- page break
- `preface/foreword`
- page break
- document type in a box (`白 紙`, (`White-paper`))

**Comment by Intelligent2013** [comment]
Scope example:
![image](https://user-images.githubusercontent.com/5559926/227313291-c9fa8ae0-affa-4844-8977-997c1eff72e5.png)

Rendering rules:
- [x] section number in Times New Roman bold
- [x] section title in IPAexGothic 
- [x] Japanese text in IPAexMincho
- [ ]English text in Times New Roman bold
- [ ] reference to Annex:
   -  the word Annex in Japanese `附属書` in IPAexGothic,
   - annex letter in Times New Roman bold
- [ ] Note title:
   -  the word Note in Japanese `注記` in IPAexGothic
   - note's number in Times New Roman bold

To do in XSLT on-fly:
- allocate text in English and digits in the tag `<font font-family="serif">...</font>`
- render `<font font-family="serif">...</font>` in Times New Roman bold
- render note/example name, xref content in IPAexGothic.
```
For instance:
```xml
<note id="_">
	<name>注記  1</name>
```
should be transformed vis XSLT on-fly to:
```
<note id="_">
	<name>注記  <font font-family="serif">1</font></name>
```

**Comment by Intelligent2013** [comment]
JIS XSLT for PDF rendering available in https://github.com/metanorma/metanorma-jis/blob/main/lib/isodoc/jis/jis.international-standard.xsl.
Further testing and updates will be in https://github.com/metanorma/metanorma-jis/issues/9.

**Comment by ronaldtse** [comment]
@Intelligent2013 regarding year formatting, it is not the year that matters, but the following:
* Numbers are in Mincho font
* Document identifiers are formatted in bold
