### ISSUE TITLE
PDF JIS Z 8301: Table 4 wrong footnote

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#41]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/228934634-3c09511a-ffbe-4d22-b9c9-381f767f74fb.png)

Rendered PDF (wrong footnote `b)`):
![image](https://user-images.githubusercontent.com/5559926/228934708-0a65c64a-f670-4bf7-be66-2407d817b2b6.png)

Adoc:
```adoc
footnote:table4a[文末で，...]
...

| 緩い禁止 footnote:table4a[]
```

**Comment by Intelligent2013** [comment]
From `https://github.com/metanorma/mn-samples-jis/blob/main/sources/jis-z-8301-2019/sections/07-presentation.adoc`:
```adoc
| 推奨
footnote:table4a[文末で，推奨を示す表現形式として，"…すべきである。"及び"…すべきでない。"は，用いない。"べき" は，"…すべき事項"のように，名詞を修飾するときだけに用いる。]
| …することが望ましい。 …するのがよい。 …することを推奨する。
| このほかでもよいが，これが特に適していることを示す。
| should 例外的に用いられている同等の表現形式it is
recommended that … ought to …

| 緩い禁止 footnote:table4a[]
| …望ましくない。 …しない方がよい。
```

The presentation XML contains the text `table4a` instead of text from named footnote 'table4a':
```xml
<tr>
  <td valign="top" align="left">
    <p id="_92e456ee-ad9b-2f1b-a221-378223a6f466">推奨<fn reference="a">
        <p id="_173fda93-dbc1-72b9-ee39-bf50d019eb9d">文末で，推奨を示す表現形式として，”…すべきである。”及び”…すべきでない。”は，用いない。”べき” は，”…すべき事項”のように，名詞を修飾するときだけに用いる。</p>
      </fn>
    </p>
  </td>
  <td valign="top" align="left">
    <p id="_361e76eb-d4d6-2a25-e82d-257feb969f97">…することが望ましい。 …するのがよい。 …することを推奨する。</p>
  </td>
  <td valign="top" align="left">
    <p id="_f0affd61-49c0-222e-5c90-babec70192d2">このほかでもよいが，これが特に適していることを示す。</p>
  </td>
  <td valign="top" align="left">
    <p id="_5ee0bd07-feac-aa22-5341-82ce10a5af6d">should 例外的に用いられている同等の表現形式it is
recommended that … ought to …</p>
  </td>
</tr>
<tr>
  <td valign="top" align="left">
    <p id="_312457ce-499f-4d53-6f25-8ed9586ef55a">緩い禁止<fn reference="b">
        <p id="_bc9772df-f910-a77c-37a0-f79efea5617a">table4a</p>
      </fn>
    </p>
  </td>
```


In https://github.com/metanorma/mn-samples-iso/blob/main/sources/international-standard/body/body-en.adoc there is a similar markup:
```adoc
| HDK | 2,0 footnote:defectsmass[The maximum permissible mass fraction of defects shall be determined with respect to the mass fraction obtained after milling.] | 2,0 | 2,0 footnote:defectsmass[] | 2,0
| Damaged kernels | 4,0 | 3,0 | 4,0 | 3,0
| Immature and/or malformed kernels | 8,0 | 2,0 | 8,0 | 2,0
| Chalky kernels | 5,0 footnote:defectsmass[] | 5,0 | Not applicable | Not applicable
```
but `footnote:defectsmass[]` process correctly.

**Comment by Intelligent2013** [comment]
The `footnote:table4a[]` doesn't process due the operator `a` in `cols="a,a,a,a"`:
```
[[table4]]
[cols="a,a,a,a",options="header"]
```

I've tried to change to `d`:
```
[[table4]]
[cols="d,d,d,d",options="header"]
```

and the Presentation XML generates correctly:
```xml
<tbody>
  <tr>
    <td align="left" valign="top">推奨
                            <fn reference="a">
        <p id="_65053866-e672-3b86-8576-b828336f93e5">文末で，推奨を示す表現形式として，”…すべきである。”及び”…すべきでない。”は，用いない。”べき” は，”…すべき事項”のように，名詞を修飾するときだけに用いる。</p>
      </fn>
    </td>
    <td align="left" valign="top">…することが望ましい。 …するのがよい。 …することを推奨する。</td>
    <td align="left" valign="top">このほかでもよいが，これが特に適していることを示す。</td>
    <td align="left" valign="top">should 例外的に用いられている同等の表現形式it is recommended that … ought to …</td>
  </tr>
  <tr>
    <td align="left" valign="top">緩い禁止
                            <fn reference="a">
        <p id="_de489f02-0641-2564-419f-f7a9dab4cda0">文末で，推奨を示す表現形式として，”…すべきである。”及び”…すべきでない。”は，用いない。”べき” は，”…すべき事項”のように，名詞を修飾するときだけに用いる。</p>
      </fn>
    </td>
```

@opoudjis is this a bug or not?

**Comment by opoudjis** [comment]
It's a known issue with footnotes: the asciidoc mode in tables processes their contents as autonomous documents. I have lodged this as an issue with asciidoc years ago, and I can do out the ticket reference for you if you want. I have no indication that it will be resolved soon.

**Comment by Intelligent2013** [comment]
@opoudjis thank you for the answer. Looks like that is issue https://github.com/asciidoctor/asciidoctor/issues/4295.

I've removed `cols="a,a,a,a",` and it solved this concrete issue. Now PDF renders so:
![image](https://github.com/metanorma/metanorma-jis/assets/5559926/3cefed61-b64b-4fae-9284-371782597e74)

**Comment by opoudjis** [comment]
This is as resolved as it will ever be...
