### ISSUE TITLE
PDF JIS Z 8301: year in the standard references

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#45]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

Original PDF (`JIS Z 8000` without year):
![image](https://user-images.githubusercontent.com/5559926/228938652-9197134d-9b27-4f72-9efb-5feeb629bad3.png)

Rendered PDF (`JIS Z 8000` with~out~ year `2014`):
![image](https://user-images.githubusercontent.com/5559926/228938698-2bf427fb-d4d2-4162-b265-9b5f7e6ef115.png)

**Comment by opoudjis** [comment]
Remember, I discovered that @andrew2net had not implemented the dropping of years in JIS references, so this is blocked by https://github.com/relaton/relaton-jis/issues/6

**Comment by opoudjis** [comment]
@Intelligent2013 Try now?

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://github.com/metanorma/metanorma-jis/assets/5559926/fef52651-b9d1-473a-b0a9-71d6b7642a37)

@opoudjis thank you.
