### ISSUE TITLE
PDF JIS Z 8301: wrong figure title rendering

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#51]
Source: https://github.com/metanorma/metanorma-jis/issues/9

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/229196039-24a76754-dc94-4f35-8bc4-9287182d8a2a.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/229196087-64a1b8a7-13f4-4119-b3d6-411acbfeb57b.png)

To do:
- set centered alignment
- set bold for figure label

**Comment by ronaldtse** [comment]
Also, the font for captions is Gothic (with Times New Roman bold for Latin text)

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/230727401-0c22f099-04f7-44c9-ba3f-c1cb238de2da.png)
