### ISSUE TITLE
PDF JIS Z 8301: unordered lists different labels

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#58]
Source: https://github.com/metanorma/metanorma-jis/issues/9

In the original PDF the different characters are using for unordered list items labels:
![image](https://user-images.githubusercontent.com/5559926/230729183-bad82aa7-a2df-4400-8c8d-9508474cf079.png)

I can't differentiate them.

**Comment by ronaldtse** [comment]
@Intelligent2013 in JIS Z 8301 it says both dash and dot bullet labels are accepted in unordered lists. However, in practice, we only see the dash bullets at the first level. Let's close this.
