### ISSUE TITLE
Word: JIS Z 5999 sample formatting

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#6]
- [x] The Foreword should be on a separate page and unnumbered. Foreword title uses style "まえがき見出し". Foreword text is in style "まえがき段落"
- [x] The Introduction should be unnumbered. The Introduction title is in style "序文". Text in 
- [x] Scope is now Clause 3 but should have been Clause 1
- [ ] the "note_label" style should be "注記１"
- [ ] "WARNING" label should be "警告". I don't know what style it uses, perhaps "注記１" would work
- [ ] the "NOTE" text (technically "Note to entry") in the Terms and definitions clause should be "注釈"
- [x] "DEPRECATED" label should be "推奨しない用語："
- [ ] the "footnote" appears now as "footnote[注 a).]" but actually should only be "a)" in superscript.
- [x] table footnotes are not appearing
- [ ] the "example-title" style should be "例１"
- [ ] (Not sure what to do with "Under preparation. (Stage at the time of publication IEC 61082-1).", does not seem covered by JIS Z 8301)

**Comment by opoudjis** [comment]
> the "example-title" style should be "例１"

Making Example style that. Without guidance, I simply don't know what the example title style is, if any.

>  the "footnote" appears now as "footnote[注 a).]" but actually should only be "a)" in superscript.

Markup error, but you have explicitly put the 注  inside the footnote.

**Comment by ronaldtse** [comment]
Funny. Not seeing all checkboxes ticked. I'll close this once verified or follow up.

**Comment by opoudjis** [comment]
I was not convinced they were even legitimate issues, and I am not able to replicate them. I'm going to do another run when I have finished with writing unit testing. But I have told you three times already that I do not want to work further on this gem, and this issue is going to be closed until you can get me genuine feedback

**Comment by ronaldtse** [comment]
- The "Introduction/序文" is placed on the same page before Clause 1, it does not exist on a separate page. The Introduction is also optional.
- The Inner cover note exists on the inner cover (not the main content doc)
- the list of contributors is shown on the inner cover page (right behind the logo cover page)
- Clause 2 is indented differently from Clause 1, it should not be the case
- Clause 3: the "note to entry" labels not in the correct font (should be in Gothic)
- Clause 9: the figure (which contains 2 subfigures) is shown broken
- Clause 9 note: label not in the correct font (should be in Gothic)
- Table 2 note: label not in the correct font (should be in Gothic)
- 12.1: note labels not in the correct font (should be in Gothic)
- 12.2/12.3: example labels not in the correct font (should be in Gothic)
- 14.1: 3rd level list item not indented correctly (it is at the 1st level indent)
- Annex A: Right now it shows as "1.	附属書 A " but should just be "附属書 A", indenting also incorrect.
- Bibliography: the "In preparation" footnote seems to be repeated at the end of the bibliography, after the main bibliography item list.

**Comment by opoudjis** [comment]
The approach taken to figures is to select elements from the figure, and render them into a figure table, one at a time. We are not currently tolerating tables within tables in Metanorma, and hopefully, we don't need to.

**Comment by ronaldtse** [comment]
> The JIS lunatic approach to encoding figures as tables is actually involving a table nested within a table. Or at least the supplied sample document does, which I do not trust at all.  

This image is from the official manual. It seems that it is not a table nested within a table, but just an image within a table.

<img width="611" alt="Screenshot 2023-03-21 at 10 37 05 PM" src="https://user-images.githubusercontent.com/11865/226640280-641eb4f7-8e6c-4ba8-86c4-204e8559421b.png">

**Comment by opoudjis** [comment]
> This image is from the official manual. It seems that it is not a table nested within a table, but just an image within a table.

You did say that, but the document you've sent me puts that image inside a table inside the table cell. (In fact, it puts them side by side as subfigures.) I'm ignoring that and doing just single table cells.

**Comment by ronaldtse** [comment]
@opoudjis I've uploaded the new document under reference-docs. Could you help check? Thanks.

**Comment by opoudjis** [comment]
I do have to note that the styling seems to be changing in small ways between iterations (e.g. normal para indent), and I won't keep adjusting it until I have an authoritative document.

**Comment by opoudjis** [comment]
Gone through foregoing batch of comments, waiting further instruction

**Comment by ronaldtse** [comment]
The latest version is much improved. There are a few remaining issues (and some regressions).

## Paragraph initial indent

We had this before but it got lost.
<img width="536" alt="Screenshot 2023-03-22 at 2 58 54 PM" src="https://user-images.githubusercontent.com/11865/226825712-5a57a18f-bc3f-4f71-bf02-0530545340ab.png">

## Introduction style

Title style should be "序文":
<img width="1078" alt="Screenshot 2023-03-22 at 3 01 43 PM" src="https://user-images.githubusercontent.com/11865/226826210-b798dc2a-64c6-4f5e-a6ef-ae1a671db931.png">

Text style should be "段落":
<img width="1045" alt="Screenshot 2023-03-22 at 3 02 16 PM" src="https://user-images.githubusercontent.com/11865/226826311-b990d489-2f67-4fcb-8681-f26871d51c09.png">

## Paragraph style

Please replace the "字下げなし段落" style with "段落". "字下げなし段落" means "unindented paragraph" which is not the correct style.

## Warning

The warning label "警告" should be in the same style as "note_label".

## Terms and defs

The "term" should use the "用語及び定義＿用語（名称）" style and font set to "MS Gothic".
<img width="589" alt="Screenshot 2023-03-22 at 3 04 44 PM" src="https://user-images.githubusercontent.com/11865/226826739-315fafcc-db77-4df3-b7d0-f73574eef661.png">

The "alt term" should be prefixed with the "代替用語:" label.

Now:
<img width="282" alt="Screenshot 2023-03-22 at 3 05 19 PM" src="https://user-images.githubusercontent.com/11865/226826855-57b8f3fe-cd1f-497d-89f9-ff920692c8ad.png">

Should be:
<img width="306" alt="Screenshot 2023-03-22 at 3 05 59 PM" src="https://user-images.githubusercontent.com/11865/226826971-5b78f943-548d-4fd6-ad76-59b8f4fd89cc.png">

The "alt term" and "deprecated term" should use the "用語及び定義＿用語（名称）" style (but there's no need to change font to "MS Gothic").

## Symbols and abbreviated terms

i18n needed for the clause titles:
<img width="291" alt="Screenshot 2023-03-22 at 3 07 59 PM" src="https://user-images.githubusercontent.com/11865/226827319-1545cfe2-32f0-4ad9-ae2c-04af08d8404b.png">

(These are defined in JIS Z 8301)
* Symbols => 記号
* Abbreviated terms => 略語
* "Symbols and abbreviated terms" => 記号及び略語
* "Terms, definitions, symbols and abbreviated terms" => 用語及び定義並びに記号及び略語

## Unnumbered lists bullets missing

<img width="517" alt="Screenshot 2023-03-22 at 3 11 13 PM" src="https://user-images.githubusercontent.com/11865/226827910-66659ed4-51af-474d-b8a0-67aa6e85fe96.png">

## Subfigure support

This clause contains 2 subfigures, but is rendered as 2 separate figures:
<img width="627" alt="Screenshot 2023-03-22 at 3 11 45 PM" src="https://user-images.githubusercontent.com/11865/226827996-6c58a9a4-53d3-4fb0-8ff1-b8056cc5e176.png">

## Figure key, notes, examples, paragraphs, footnotes

These items should be rendered inside the "table" that wraps the figure. See the Word doc or the JDT2019 manual.

In a figure, these items are wrapped in cells but with hidden borders.

## Table key, notes, examples, paragraphs, footnotes

These items should be rendered inside the "table" that wraps the table. See the Word doc or the JDT2019 manual.

In a table, these items are wrapped in cells but with outer borders.

## Annex

<img width="646" alt="Screenshot 2023-03-22 at 3 14 30 PM" src="https://user-images.githubusercontent.com/11865/226828462-1ab83914-ca0e-4980-9aa4-32962484d391.png">

Issues:
* Heading contains a stray newline between "normative" and the title
* Annex clause headings not applied the correct style (should be same as normal clause title)

**Comment by opoudjis** [comment]
Terms and defs treatment of boldface: the real solution here is to replace boldface from Metanorma with MS Gothic, but only for spans of Japanese text.

**Comment by opoudjis** [comment]
> Figure key, notes, examples, paragraphs, footnotes
> These items should be rendered inside the "table" that wraps the figure. See the Word doc or the JDT2019 manual.

Separating notes, examples, paragraphs, and parsing them in order of encounter, lumping adjacent elements of same type in the one row.

**Comment by opoudjis** [comment]
I am declining to implement the requested rearrangement of content around tables. Unlike the case for figures, there is no precedent for or markup to incorporate what is being requested for tables in Metanorma short of shoving content into the table footer (which has *not* currently been done); the requested changes are far too drastic, and this gem has already been an inexcusable time sink.

**Comment by ronaldtse** [comment]
@opoudjis requested to move the remaining issues to new independent issues. We'll close this one since it is reasonably well working. Thank you!
