### ISSUE TITLE
Ranges localization

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#61]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9, https://github.com/metanorma/metanorma-jis/issues/38

For adoc (https://github.com/metanorma/mn-samples-jis/blob/update/sources/jis-z-8301-2019/sections/07-presentation.adoc):
```
<<from!table3;to!table6>>
```
presentation XML:
```xml
<xref target="table3">表 <span class="citetbl">3</span>
</xref> to <xref target="table6">
	<span class="citetbl">6</span>
</xref>
```
PDF:
![image](https://user-images.githubusercontent.com/5559926/230793324-af768326-0eac-4343-b461-fc76f9e1dd2c.png)

Expected XML:
```xml
<xref target="table3">表<span class="citetbl">3</span></xref>～<xref target="table6">表<span class="citetbl">6</span></xref>
```

**Comment by Intelligent2013** [comment]
I've updated expected XML format:
```xml
<xref target="table3">表<span class="citetbl">3</span></xref>～<xref target="table6">表<span class="citetbl">6</span></xref>
```

**Comment by opoudjis** [comment]
Right, so in Japanese it's not just "Table 3~6", but "Table 3~Table 6".

We have in xrefs combinations `can_conflate_xref_rendering?()` for locations. If it is true, then there is one location type, and a combination of values, e.g. Table 3-6. Table 3 ~ Table 6 is no different from Table 3 ~ Note 4: if the location is repeated for each component, then there is no conflation, which means that conflation can be globally false for a language. I will set that for Japanese by `no_conflate_xref_locations` as an i18n value.

**Comment by opoudjis** [comment]
`<xref target="ref1">箇条 1</xref>～<xref target="ref2">箇条 2</xref>` for "Clause 1 to 2".
