### ISSUE TITLE
Spärdruck on brief titles

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-jis#62]
There is an issue specific to Japanese, which I do NOT believe should be resolved by l10n, but by postprocessing.

Japanese imposes Spärdruck (extra spaces between characters, crudely realised with added spaces) on very short titles. So the title of a Commentary appears as 

![image](https://user-images.githubusercontent.com/1911039/230814314-25a2eac1-09b4-40b7-913b-64f1b63805a3.png)

However, the l10n string for "Commentary" shall be 解説. It appears without the space, for example, in page footers.

Instead, I will implement postprocessing in JIS, which inserts the `&#x3000;` character between characters in very brief section titles (< 4 characters). It will only appear in titles, not in crossreferences.

This captures CJK https://www.w3.org/TR/clreq/#principles_of_arrangement_of_han_characters https://www.w3.org/TR/clreq/#procedures_for_inter-character_space_expansion

> To achieve a balance between running heads with different numbers of characters, increased inter-character spacing is used for running heads with few characters.

—although no guidance is given as to how many characters are "few". Adding `&#x3000;`  is a crude realisation of Spärdruck, but it's what JIS are doing; the Word option to do that properly (kerning) is unfamiliar to people.

@ronaldtse Please confirm that < 4 characters for inserting extra spacing is reasonable.

**Comment by opoudjis** [comment]
Do not do Spärdruck on:

Per incomplete https://www.w3.org/TR/clreq/#prohibition_rules_for_unbreakable_marks

* U+2014 U+2014
* U+2026 U+2026
* U+22EF U+22EF
* "Digits and their Prefix and Suffix" (?)
* "Annotation Marks"

Per https://www.w3.org/TR/jlreq/?lang=en#unbreakable_character_sequences

* U+2014 U+2014
* U+2026 U+2026
* U+2025 U+2025
* Between European numerals
* Prefixed abbrev (https://www.w3.org/TR/jlreq/?lang=en#cl-12) and numeral (Arabic or ideographic)
* (Arabic or ideographic) Number and Postfixed abbrev (https://www.w3.org/TR/jlreq/?lang=en#cl-13)
* Between Latin characters
* Certain punctuation

The Chinese spec is lagging the Japanese spec in completeness and, frankly, coherence. We will apply the Japanese spec, the principles are clearly the same. 

Spärdruck will be applied universally to titles at first level, and equivalent headings (e.g. cover pages), in CJK.

**Comment by ronaldtse** [comment]
In fact this also occurs for contributor names:
<img width="742" alt="Screenshot 2023-04-11 at 7 34 15 AM" src="https://user-images.githubusercontent.com/11865/231018815-8ba54615-7eea-4fe2-9925-1480ca323674.png">

The surname and given name are justified to 3 spaces wide.

**Comment by opoudjis** [comment]
OK, but much of this has to be the user's problem. I'm limiting this to section titles and headings, which are either auto-text, or which can be cited as cross-references (which would not warrant expanded text). If they're likely to be treated as auto-text, I intervene. I can't intervene everywhere, and certainly not in a context like that.
