### ISSUE TITLE
Investigate Commentary section having separate page numbers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#63]
> ... I've copied the header across, and it's not working; my very strong suspicion is that this functionality is not supported in DOC at all. Then again, it's not working correctly in the sample document of 5999 in DOCX either (it's frozen on "Comm. 2" as the page number every second page of the commentary), and my very strong suspicion is that it's manually set by JIS. Will not fix, we would need to see a working example, and I am not convinced this genuinely is Word functionality to begin with.

Please see this for a the Commentary having separate page numbers:
* https://github.com/metanorma/mn-samples-jis/tree/main/reference-docs/TR-X-0067-2002

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-jis/issues/28#issuecomment-1502596058_

**Comment by opoudjis** [comment]
In the provided document, the page number of the commentary is calculated by substracting the page count of the document up to the page before the commentary, from the page count of wherever we are in the commentary:

<img width="597" alt="Screenshot 2023-05-21 at 12 55 59" src="https://github.com/metanorma/metanorma-jis/assets/1911039/5713e88b-0c2d-4be5-89b9-903b32302293">

The catch is, that DOCPROPERTY 解説P is hard-coded in the document: it is manually entered in the document properties tab. If you add or remove pages to the main section of the document, the commentary page number will start counting from a number other than 1; I am currently getting page -5. It is not a dynamic quantity.

Moreover, it is not a dynamically computed quantity: that value is being set manually. If the macro language of Word is not expressive enough, we may not be able to calculate that value at all.

**Comment by opoudjis** [comment]
https://gregmaxey.com/word_tip_pages/page_numbering.html

You can do this by putting a bookmark at the end of the previous section, and subtracting its PAGEREF from the current page number.
