### ISSUE TITLE
PDF JIS Z 8301: static or dynamic text on the cover page

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#64]
Source: https://github.com/metanorma/metanorma-jis/issues/9

On the cover page there are texts:

![image](https://user-images.githubusercontent.com/5559926/231499713-9e45b5eb-70e7-420a-88b8-4573d055a753.png)

![image](https://user-images.githubusercontent.com/5559926/231499786-b2d463b3-9be9-4a99-92cb-46f51520cf07.png)
(translation: Japan Industrial Standards Survey Council deliberations)

![image](https://user-images.githubusercontent.com/5559926/231499815-7575a1bb-3ab3-446c-8883-eeb40285c633.png)
(translation: (Issued by the Japan Standards Association))

@ronaldtse is it static text or should be set in the document attributes?

**Comment by Intelligent2013** [comment]
I've checked another documents in https://github.com/metanorma/mn-samples-jis/tree/main/reference-docs.
It's dynamic text. I'll analyze all cover pages.

**Comment by ronaldtse** [comment]
These 3 texts should be encoded in document attributes.

**Comment by Intelligent2013** [comment]
The cover page text encoded in these attributes:
```adoc
:publishing-organization-abbr: JSA
:publishing-organization-name-ja: 日本規格協会
:publishing-organization-name-en: Japanese Standards Association
:investigation-organization-name-ja: 日本産業標準調査会
:investigation-organization-name-en: Japanese Industrial Standards Committee
:investigation-committee-name: 日本産業標準調査会 標準第一部会
```
but looks like metanorma-jis doesn't support them yet.
On hold.

**Comment by opoudjis** [comment]
Just implemented, but I have changed the attribute names to make them consistent with Metanorma.

**Comment by ronaldtse** [comment]
> Just implemented, but I have changed the attribute names to make them consistent with Metanorma.

So what are the attribute names now? Thanks.

**Comment by ronaldtse** [comment]
Because we need to update all the sample documents. Ping @opoudjis @metanorma/editors

**Comment by ronaldtse** [comment]
@opoudjis informs that:
> I've renamed them "investigative" in the implementation

So they should now be:
```
:publishing-organization-abbr: JSA
:publishing-organization-name-ja: 日本規格協会
:publishing-organization-name-en: Japanese Standards Association
:investigative-organization-name-ja: 日本産業標準調査会
:investigative-organization-name-en: Japanese Industrial Standards Committee
:investigative-committee-name: 日本産業標準調査会 標準第一部会
```

**Comment by Intelligent2013** [comment]
From https://github.com/metanorma/metanorma-jis/issues/103#issuecomment-1679096421:

> This needs isodoc and metanorma-iso
>
> Input:
> 
> ````
> = A
> :publisher-abbr: JSA
> :publisher-ja: 日本規格協会
> :publisher-en: Japanese Standards Association
> :investigation-organization-ja: 日本産業標準調査会
> :investigation-organization-en: Japanese Industrial Standards Committee
> :investigation-committee: 日本産業標準調査会 標準第一部会
> :docnumber: 1
> ````
> 
> Output:
> 
> ````
> <bibdata type="standard">
> 	<docidentifier type="JIS">1:2023</docidentifier>
> 	<docnumber>1</docnumber>
> 	<contributor>
> 		<role type="author"/>
> 		<organization>
> 			<name>
> 				<variant language="ja">日本規格協会</variant>
> 				<variant language="en">Japanese Standards Association</variant>
> 			</name>
> 			<abbreviation>JSA</abbreviation>
> 		</organization>
> 	</contributor>
> 	<contributor>
> 		<role type="publisher"/>
> 		<organization>
> 			<name>
> 				<variant language="ja">日本規格協会</variant>
> 				<variant language="en">Japanese Standards Association</variant>
> 			</name>
> 			<abbreviation>JSA</abbreviation>
> 		</organization>
> 	</contributor>
> 	<contributor>
> 		<role type="authorizer">
> 			<description>Investigative organization</description>
> 		</role>
> 		<organization>
> 			<name>
> 				<variant language="ja">日本産業標準調査会</variant>
> 				<variant language="en">Japanese Industrial Standards Committee</variant>
> 			</name>
> 		</organization>
> 	</contributor>
> 	<contributor>
> 		<role type="authorizer">
> 			<description>Investigative committee</description>
> 		</role>
> 		<organization>
> 			<name>日本産業標準調査会 標準第一部会</name>
> 		</organization>
> 	</contributor>
> ````

> FYI @Intelligent2013 : `<variant>` is the Metanorma way of differentiating the same string content in different languages, but you haven't seen it until now, because I normalise it in Presentation XML to "variant1/variant2". I've just stopped doing that normalisation within bibdata, but I'm pretty sure this is the only place I am using it in bibdata. (I did not use it for titles, because I devised `variant` later.)


Tasks for me:
- [ ] update `document,adoc` for JIS Z 8301
- [ ] update JIS XSLT for `variant` titles

**Comment by Intelligent2013** [comment]
@ronaldtse I'm confused. What is the option correct?

> 
> So they should now be:
> 
> ```
> :publishing-organization-abbr: JSA
> :publishing-organization-name-ja: 日本規格協会
> :publishing-organization-name-en: Japanese Standards Association
> :investigative-organization-name-ja: 日本産業標準調査会
> :investigative-organization-name-en: Japanese Industrial Standards Committee
> :investigative-committee-name: 日本産業標準調査会 標準第一部会
> ```


From https://github.com/metanorma/metanorma-jis/issues/103#issuecomment-1679096421:
> ```
> :publisher-abbr: JSA
> :publisher-ja: 日本規格協会
> :publisher-en: Japanese Standards Association
> :investigation-organization-ja: 日本産業標準調査会
> :investigation-organization-en: Japanese Industrial Standards Committee
> :investigation-committee: 日本産業標準調査会 標準第一部会
> ```

**Comment by ronaldtse** [comment]
@opoudjis please answer @Intelligent2013 , thanks!

**Comment by Intelligent2013** [comment]
The currently working variant is 2nd:
```adoc
:publisher-abbr: JSA
:publisher-ja: 日本規格協会
:publisher-en: Japanese Standards Association
:investigation-organization-ja: 日本産業標準調査会
:investigation-organization-en: Japanese Industrial Standards Committee
:investigation-committee: 日本産業標準調査会 標準第一部会
```

**Comment by ronaldtse** [comment]
@Intelligent2013 I believe @opoudjis has already changed `investigation` to `investigative`.

@opoudjis can you please confirm?

**Comment by opoudjis** [comment]
Yes, I changed it because I saw that he instructed you to use investigative: https://github.com/metanorma/metanorma-jis/pull/112/files

I just hadn't gotten around to merging the PR.

**Comment by Intelligent2013** [comment]
@opoudjis  thank you!

@ronaldtse do you know why these fields were introduced into `document.adoc` ?
```
:investigation-committee-representative-name: 酒井 信介
:investigation-committee-representative-role: 部会長
```

I've found these data on the inner cover page only:
![image](https://github.com/metanorma/metanorma-jis/assets/5559926/8af84bc0-9a1c-47f7-9602-cb4d8046fc01)

But it encoded in the `00-preface.adoc` in the contributors table as text:
```adoc
[.preface,type=contributors]
== {blank}

.日本産業標準調査会標準第一部会 構成表
[cols="25a,32a,105a",options="header,unnumbered"]
|===
| | 氏名 | 所属

| (部会長) | span:surname[酒井] span:givenname[信介] | 横浜国立大学
...
```
Can I remove it from `document.adoc`?

**Comment by Intelligent2013** [comment]
> - [ ] update `document.adoc` for JIS Z 8301

Will be done in https://github.com/metanorma/mn-samples-jis/issues/12.
