### ISSUE TITLE
Support multilevel list numbering

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#78]
Source issue: https://github.com/metanorma/metanorma-jis/issues/52

From `23.3 付番及び区分け` (https://github.com/metanorma/mn-samples-jis/blob/main/reference-docs/JIS-Z-8301-2019/jis_z_08301_000_000_2019_j_ed10_ch.pdf):
![image](https://user-images.githubusercontent.com/5559926/236237142-1359bc4b-7457-471c-9b67-7bfcc070f6db.png)

JIS uses the multi-level numbering like `1.1`, `1.2`, etc.

**Comment by opoudjis** [comment]
Update xrefs in JIS to use multi-level.

Insert xref of li as "label" attribute of li in Presentation XML.

**Comment by opoudjis** [comment]
Differentiate bare_xref in anchor from label. Label is the label of the item. bare_xref is the barest cross-ref (used to compose compound xrefs), stripped of almost everything; but for a list item, label is 1, bare_xref is 1).

**Comment by opoudjis** [comment]
So @Intelligent2013 all ol/li will have a "label" attribute in Presentation XML, just in case you need this elsewhere.

**Comment by opoudjis** [comment]
So: `<li id="..." label="1.1.2">`
