### ISSUE TITLE
Use pubid-jis in metanorma-jis

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-jis#8]
pubid-jis gem is now ready for use, as per: https://github.com/metanorma/pubid-jis/issues/1

Usage:
* https://github.com/metanorma/pubid-jis#usage

**Comment by opoudjis** [comment]
@mico Until you release pubid-jis, I cannot progress this.

Be aware that, per the request of @Intelligent2013, I will be stripping the initial `JIS ` from the identifier. As far as I can tell, that is universal to JIS identifiers, and does not cause  any issues.

**Comment by ronaldtse** [comment]
> I will be stripping the initial JIS  from the identifier. As far as I can tell, that is universal to JIS identifiers, and does not cause any issues.

I believe it would make sense for pubid-jis to provide a mechanism to not give the JIS prefix, because it is one of the basic needs on the cover page.

**Comment by opoudjis** [comment]
> I believe it would make sense for pubid-jis to provide a mechanism to not give the JIS prefix, because it is one of the basic needs on the cover page.

A comment for pubid-jis, not for metanorma-jis

**Comment by opoudjis** [comment]
Pending: `.to_s(with_publisher: false)`

**Comment by opoudjis** [comment]
Waiting for next pubid-jis release

**Comment by ronaldtse** [comment]
@mico can we please release the new gem? Thanks.
