### ISSUE TITLE
PDF JIS Z 8301: fix informative annexes

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#80]
Source issue: https://github.com/metanorma/metanorma-jis/issues/9

Original PDF:
![image](https://user-images.githubusercontent.com/5559926/236515245-2b2c6889-5373-466f-85ad-bb43a5b12aea.png)

Generated PDF - all annexes are normative:
![image](https://user-images.githubusercontent.com/5559926/236515530-aa3331cb-803c-45ba-8075-51cf2de0348e.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 is this an mn-samples-jis encoding problem? Or Metanorma XML?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 is this an mn-samples-jis encoding problem? Or Metanorma XML?

@ronaldtse encoding problem. `obligation=informative` is missing.

**Comment by Intelligent2013** [comment]
Updated in https://github.com/metanorma/mn-samples-jis/pull/10/.
